//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GilmetdinovaHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR()
        {
            this.MEDICALHISTORY = new HashSet<MEDICALHISTORY>();
            this.OPERATION = new HashSet<OPERATION>();
        }
    
        public int DOCTOR_ID { get; set; }
        public string DOCTOR_SURNAME { get; set; }
        public string DOCTTOR_NAME { get; set; }
        public string DOCTOR_PATRONYMIC { get; set; }
        public int DOCTOR_POST_ID { get; set; }
        public Nullable<System.DateTime> DOCTOR_EXPERIENCE_DATA { get; set; }
        public Nullable<int> DOCTOR_EXPERIENCE { get; set; }
        public string DOCTOR_SCIENTIFIC { get; set; }
        public string DOCTOR_ADRESS { get; set; }
        public Nullable<decimal> DOCTOR_SALARY { get; set; }
        public string MainImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICALHISTORY> MEDICALHISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPERATION> OPERATION { get; set; }
        public virtual POST POST { get; set; }
        public string POST_NAME_STR
        {
            get
            {
                return this.POST?.POST_NAME ?? "Отделение не найдено";
            }
        }
    }
}