//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GilmetdinovaHospital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GilmetdinovaHospitalEntities : DbContext
    {


        private static GilmetdinovaHospitalEntities _context;

        public static GilmetdinovaHospitalEntities GetContext()
        {
            if (_context == null)
                _context = new GilmetdinovaHospitalEntities();

            return _context;
        }
        public GilmetdinovaHospitalEntities()
            : base("name=GilmetdinovaHospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOCTOR> DOCTOR { get; set; }
        public virtual DbSet<MEDICALHISTORY> MEDICALHISTORY { get; set; }
        public virtual DbSet<OPERATION> OPERATION { get; set; }
        public virtual DbSet<PATIENT> PATIENT { get; set; }
        public virtual DbSet<POST> POST { get; set; }
        public virtual DbSet<TREATMENTLIST> TREATMENTLIST { get; set; }
    }
}
