//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GilmetdinovaHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICALHISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICALHISTORY()
        {
            this.TREATMENTLIST = new HashSet<TREATMENTLIST>();
        }
    
        public int MEDICALHISTORY_ID { get; set; }
        public int MEDICALHISTORY_DOCTOR_ID { get; set; }
        public int MEDICALHISTORY_PATIENT_ID { get; set; }
        public string MEDICALHISTORY_DIAGNOSIS { get; set; }
        public System.DateTime MEDICALHISTORY_DATEOFFILLNESS { get; set; }
        public System.DateTime MEDICALHISTORY_DATEOFFRECOVERY { get; set; }
        public string MEDICALHISTORY_VIEWOFFTREARMENT { get; set; }
        public Nullable<int> MEDICALHISTORY_OPERATION_ID { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual PATIENT PATIENT { get; set; }
        public virtual OPERATION OPERATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TREATMENTLIST> TREATMENTLIST { get; set; }
    }
}
