//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GilmetdinovaHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPERATION()
        {
            this.MEDICALHISTORY = new HashSet<MEDICALHISTORY>();
        }
    
        public int OPERATION_ID { get; set; }
        public string OPERATION_DESCRIPTION { get; set; }
        public int OPERATION_DOCTOR_ID { get; set; }
        public System.DateTime OPERATION_DATE { get; set; }
        public string OPERATION_RESULT { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICALHISTORY> MEDICALHISTORY { get; set; }
    }
}
