//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GilmetdinovaHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREATMENTLIST
    {
        public int TREATMENTLIST_ID { get; set; }
        public System.DateTime TREATMENTLIST_DATE { get; set; }
        public int TREATMENTLIST_MEDICALHISTORY_ID { get; set; }
        public string TREATMENTLIST_MEDICINES { get; set; }
        public string TREATMENTLIST_TEMPERATURE { get; set; }
        public string TREATMENTLIST_PRESSURE { get; set; }
        public string TREATMENTLIST_PATIENTSCONDITION { get; set; }
    
        public virtual MEDICALHISTORY MEDICALHISTORY { get; set; }
    }
}
